### ISSUE TITLE
Include distribution changelog information between reviews.

### ISSUE THREAD

**Issue by rcaputo** [perlorg/perlweb#111]
cpanratings.perl.org doesn't reflect whether ratings have been addressed by developers.

If the changelogs for each release were inserted in the ratings timeline, the developers' attention to feedback (or lack of it) would become apparent.

Positive example:

```
[Module (version 2) changelog]
Fixed a case where widgets explode and kill the user.

[Rating (version 1) (2 releases ago, CCYY-MM-DD)]
This module is stupid and dangerous. Kills users with widget shrapnel.
```

Negative example:

```
[Module (version 3) changelog]
Updated the donations link.

[Module (version 2) changelog]
Fixed a POD typo.

[Rating (version 1) (3 releases ago, CCYY-MM-DD)]
This module is stupid and dangerous. Kills users with widget shrapnel.
```

**Comment by rspier** [comment]
Bulk closing all cpanratings issues, as the site has been in read-only mode for over a year.  https://log.perl.org/2018/06/cpan-ratings-read-only.html
