### ISSUE TITLE
CPAN Ratings Not Recognizin BitCard Login

### ISSUE THREAD

**Issue by theory** [perlorg/perlweb#160]
I wanted to review PerlIO::gzip, so went to cpanratings, hit login, logged into bit card, was redirected to cpanratings, where it just asked me to login again. And again. And again. :-(

Also, wanted to find out where to complain, but the link to http://cpanratings.perl.org/siteinfo.html 404s.

**Comment by openstrike** [comment]
This is the same behaviour I see. Initially spotted it earlier in the week - didn't report it as it could have just been transient and/or just me.

**Comment by abh** [comment]
Hi @theory and @openstrike -- please give it a try again!

**Comment by openstrike** [comment]
Confirmed as fixed for me - "Login" now changes to "Logout" in the menu bar and I am able to vote on reviews again.

Thanks, @abh.

**Comment by theory** [comment]
Yeah, works now, thanks, @abh. The site info link is still a 404, though.

**Comment by abh** [comment]
@theory -- thanks, it'll go somewhere more useful now.
