### ISSUE TITLE
Upgrading to latest version 

### ISSUE THREAD

**Issue by athirajiji** [perlorg/perlweb#162]
Hi Team, 

 As part of PRDR Upgrade we need to update current Versions to Latest Versions which is supported for AIX7.1 Server(Latest) and Oracle Database 11.2.0.4(Latest). 

 Please suggest the latest versions can be supported for AIX7.1 Server(Latest) and Oracle Database 11.2.0.4(Latest) for these softwares. 

 PERL- Current version is v5.8.0 and  latest version is 5.22.0
 

 Thanks 
 Athira

**Comment by ranguard** [comment]
I'm not sure I understand the question, but if you are asking what version of Perl you should use if you are upgrading... I'd go for 5.20.2 (5.20 was release 2014-05-27) or 5.22 (released 2015-06-01)

Perl should run on AIX as far as I know.

I'm not sure how this relates to what Database you use, the DBI ( https://metacpan.org/pod/DBI ) and modules that use it, such as DBIx::Class ( https://metacpan.org/pod/DBIx::Class ) won't change between recent versions Perl ( they try to be very backwards compatible ).

Do comment and I'll open the ticket again if this doesn't answer your question

**Comment by athirajiji** [comment]
Hi  Team,

Please suggest the current versions can be supported for AIX7.1 Server(Latest) and Oracle Database 11.2.0.4(Latest) and Oracle Database 12c and the latest versions can be supported for Oracle Database 12c and is there any support available for Oracle Database 12c from your side.


Software

Current Version

Latest Version

PERL

v5.8.0

5.22.0



Thanks,
Athira

**Comment by MartinMcGrath** [comment]
@athirajiji this isn't a perl support forum. This is the Perl web repository. Your issue seems not to relate to perl web. If you have a question about Perl generally try perlmons.org or stackoverflow.

**Comment by athirajiji** [comment]
Hi,

I logged a ticket in the site ‘GitHub’ for an issue and i got response from Leo Lapworth.Please see the mail below and am satisfied with the comments. So if i need to log a new issue (that is of same kind of old one)i logged in the same site as well as informed through a mail. Please suggest a site or please redirect this issue to the same person ‘Leo Lap worth’.We are going to upgrade the perl software to the latest version,so just we need to know the answer for the below mail.

Thanks,
Athira
From: Jiji, Athira
Sent: Wednesday, August 12, 2015 5:03 AM
To: perlorg/perlweb; perlorg/perlweb
Subject: RE: [perlweb] Upgrading to latest version (#162)

Hi  Team,

Please suggest the current versions can be supported for AIX7.1 Server(Latest) and Oracle Database 11.2.0.4(Latest) and Oracle Database 12c and the latest versions can be supported for Oracle Database 12c and is there any support available for Oracle Database 12c from your side.


Software

Current Version

Latest Version

PERL

v5.8.0

5.22.0



Thanks,
Athira

**Comment by ranguard** [comment]
@athirajiji - @MartinMcGrath is correct, this isn't really the right place for these questions, but I was just trying to help you out and understand the question, incase it did actually relate to this repository.

Btw, I think the answer is upgrade to 5.20.2 and test it from there.

**Comment by athirajiji** [comment]
Thankyou.
