### ISSUE TITLE
Upgrading to latest version 

### ISSUE THREAD

**Issue by athirajiji** [perlorg/perlweb#163]
Hi  Team,

Please suggest the current versions can be supported for AIX7.1 Server(Latest) and Oracle Database 11.2.0.4(Latest) and Oracle Database 12c and the latest versions can be supported for Oracle Database 12c and is there any support available for Oracle Database 12c from your side.

Software	Current Version	Latest Version
PERL	v5.8.0 	                   5.22.0

Thanks,
Athira

**Comment by MartinMcGrath** [comment]
Please don't duplicate posts. See your other closed issue, and the existing responses:

https://github.com/perlorg/perlweb/issues/162

**Comment by athirajiji** [comment]
Team,

Please suggest where i can log a new issue,i can see the ticket #162 is closed.I nee to log a new issue.Please provide an email address or site address.


Thanks,
Athira

**Comment by MartinMcGrath** [comment]
Is your issue to do with any of the perl websites listed at http://noc.perl.org? If not then read my advice from your previous incident.

**Comment by abh** [comment]
@athirajiji ActiveState (among other companies) support for Perl on AIX (and other platforms): http://www.activestate.com/activeperl
