### ISSUE TITLE
Cannot alter stale review

### ISSUE THREAD

**Issue by benkasminbullock** [perlorg/perlweb#170]
I have a review here:

http://cpanratings.perl.org/dist/IWL

This review seems stale to me, so I think it's better to just junk it, but I'm not allowed to alter or delete it. The precise problem is that on the edit screen:

http://cpanratings.perl.org/rate/?distribution=IWL

it says "Version required" in red.

**Comment by benkasminbullock** [comment]
Similar for this:

http://cpanratings.perl.org/rate/?distribution=Flickr-Simple

**Comment by abh** [comment]
I deleted those reviews. Patches to automatically hide reviews from non-existent distributions might make sense (though I suspect it could be more complicated than it’d first appear).

**Comment by benkasminbullock** [comment]
Closing due to read-only.
