### ISSUE TITLE
No edit button for "hidden" review

### ISSUE THREAD

**Issue by benkasminbullock** [perlorg/perlweb#171]
On this review:

http://cpanratings.perl.org/dist/Unicode-EastAsianWidth

if I click on "I hidden unhelpful review", the review appears, but there is no "edit" button on it.

If I go to "search.cpan.org" I can edit the review text by clicking on "rate this distribution".

http://cpanratings.perl.org/rate/?distribution=Unicode-EastAsianWidth

**Comment by benkasminbullock** [comment]
Also, it seems to be pulling the text out of some cache rather than the database. I deleted the review text, because I really don't use that module any more, and I'm not interested in it, but even after repeatedly reloading the page, I could not view the updated text, but just kept getting the old text.

**Comment by benkasminbullock** [comment]
Sorry, hit the "close and comment" by mistake.

**Comment by abh** [comment]
Patches welcome.

**Comment by benkasminbullock** [comment]
Closing due to read-only.
