### ISSUE TITLE
Allow to browse more reviews

### ISSUE THREAD

**Issue by zoffixznet** [perlorg/perlweb#172]
It would be nice if the homepage had some sort of "Next" button that would give you the next page of reviews, just like you can see on the homepage (the "recent reviews").

It would be useful to browse through a bunch of reviews, because you might come across a well-rated module you've not heard of (and negative reviews are often amusing to read as well).

Currently, however, only a handful of reviews are visible.

**Comment by abh** [comment]
I think my thought was that you’d navigate it by distribution, or some other grouping that was more meaningful than “whatever is latest”. That being said, patches welcome!

**Comment by zoffixznet** [comment]
Probably won't have the time until after New Years, but if no one submits a PR by then, I'll do it

**Comment by rspier** [comment]
Bulk closing all cpanratings issues, as the site has been in read-only mode for over a year.  https://log.perl.org/2018/06/cpan-ratings-read-only.html
