### ISSUE TITLE
Spammy link in a CPAN Ratings review

### ISSUE THREAD

**Issue by ap** [perlorg/perlweb#173]
This looks like legit review, but it sports a signature consisting of a link:

<http://cpanratings.perl.org/dist/Mojolicious#12310>

The site behind the link (businesscontactsnumbers.co.uk) is not a homepage or personal weblog or profile or anything of the sort. On top of that it’s full of repeated keywords, so it looks like a parking page or SEO farm of some kind, not like a legitimate business.

It’s quite possible the entire review was concocted just for the opportunity to slip in that link without anyone paying enough attention to object. However, it *was* hand-written for CPAN Ratings, unlike other cases I have seen where relevant copy from elsewhere is copy-pasted as camouflage. At least Google does not reveal it to exist anywhere else on the web.

I suggest leaving the review up, but editing it to remove the link.

**Comment by abh** [comment]
Thanks. I deleted it; I didn’t have a reasonable way to edit it.

Ask
