### ISSUE TITLE
New perl.org mailing address

### ISSUE THREAD

**Issue by coke** [perlorg/perlweb#175]
Can we get a perl6-security-report at perl.org address (list?) created (similar to the perl5 variant, closed subscription, unarchived),  with some members from the Perl 6 dev team, in anticipation of our upcoming Christmas release? I can provide some email addresses under separate cover.

Apologies if this is the wrong place to ask.

**Comment by rspier** [comment]
This is the wrong place to ask.   No worries.  Please email webmaster@ and we'll discuss.
