### ISSUE TITLE
remove /category pages

### ISSUE THREAD

**Issue by bjakubski** [perlorg/perlweb#186]
I think "category" pages (for example http://lists.perl.org/category/community.html) are no longer necessary. They appear to be superseded by tags and tags pages. They are not linked anywhere as far as I can see nor I can google them. List of mailing lists in particular categories (categories.html) is very outdated - lots of not only defunct but simply non-existent lists there. 

I believe all those html pages can be removed from repo along with categories.html. Probably "Category" field in lists.json can be removed too.

I'm willing to do that if someone can confirm my findings are correct :-)

**Comment by rspier** [comment]
In the last 30 days, there were only 3 pages hit for 6 unique pageviews.
Same for the past 3 months.
Since 1/1/2015, 4 pages, 7 unique pageviews.

I think the pages can be removed.

**Comment by rspier** [comment]
Bulk closing all cpanratings issues, as the site has been in read-only mode for over a year.  https://log.perl.org/2018/06/cpan-ratings-read-only.html
