### ISSUE TITLE
http://perldoc.perl.org/ is down (

### ISSUE THREAD

**Issue by LuckySB** [perlorg/perlweb#212]
Forbidden

You don't have permission to access / on this server.

Apache/2.2.15 (Red Hat) Server at perldoc.perl.org Port 80

**Comment by disemvoweled** [comment]
Seems to affect subdirectories as well: http://perldoc.perl.org/perlre.html

Forbidden
You don't have permission to access /perlre.html on this server.
_Apache/2.2.15 (Red Hat) Server at perldoc.perl.org Port 80_

**Comment by ranguard** [comment]
Seems ok now?
