### ISSUE TITLE
Dependency problems

### ISSUE THREAD

**Issue by benkasminbullock** [perlorg/perlweb#214]
Nothing much seems to be happening with the cpan ratings bugs, so I tried installing it myself to see if I could do something about the problems. There are several problems with the installation. First of all, the following modules seem to be necessary

DBIx::Class::Helper::Row::ToJSON
DBIx::Class::Schema

which were not installed when following the instructions.

Also the database continually fails to rebuild since it does not have "if not exists" statements after the "create table" statements, so each time the database has to be completely deleted and then started again from scratch each time one or the other things fail.

Finally this module failed to install:

DateTime::Format::SQLite

so I was stumped, and at this point I gave up.

This comment in combust.conf.sample looks wrong to me;

    # default port is 8225
    port = 8230

I will try to install this again later, from scratch again.

**Comment by abh** [comment]
Did you try the docker image? (Or maybe we didn't commit that to the repository?)


Ask



-- 
http://askask.com/

**Comment by benkasminbullock** [comment]
I haven't tried that yet, I found the problem with the DateTime:: module reported here:

https://rt.cpan.org/Ticket/Display.html?id=120422

I will try again tomorrow.

**Comment by benkasminbullock** [comment]
Closing since site is read-only now.
