### ISSUE TITLE
cpanratings - "Was this review helpful" links do not work

### ISSUE THREAD

**Issue by Grinnz** [perlorg/perlweb#232]
Either on the home page or on a dist page, the "Yes" and "No" links do not appear to be functional.

**Comment by openstrike** [comment]
Same for me. The JS console says "TypeError: $(...).live is not a function" and points to http://st.pimg.net/perlweb/cpanratings/cpanratings.v50c16fa.js line 52 col 3 as the culprit. That line appears to be:

```
 $("span.helpful").live('click', function(ev) {
```

The error occured for me today using Firefox 53.0.2.

**Comment by Grinnz** [comment]
This is becoming a problem, as useless/spammy reviews like http://cpanratings.perl.org/dist/YAML#13142 can't be voted out of view.

**Comment by rspier** [comment]
The Yes and No links are gone since the site went read-only.   No longer an issue.
