### ISSUE TITLE
pimg.net certificate expiry causing problems for perl web presence

### ISSUE THREAD

**Issue by MartinMcGrath** [perlorg/perlweb#238]
The pimg.net CDN upon which a lot of the perl web precence depends has certificate which has expired:

`st.pimg.net uses an invalid security certificate.The certificate expired on July 1, 2017 at 8:53 PM. The current time is July 3, 2017 at 9:40 AM.Error code: SEC_ERROR_EXPIRED_CERTIFICATE`

As such browsers are refusing to download much of the content required to render pages.

Screenshot attached

![2017-07-03-165617_1024x600_scrot](https://user-images.githubusercontent.com/1374568/27800297-a84a3376-6010-11e7-8531-cc74d99b783a.png)

**Comment by rspier** [comment]
Thanks, we're aware of the issue and are working to resolve it.

**Comment by abh** [comment]
Fixed!
