### ISSUE TITLE
perl speaks non-mem

### ISSUE THREAD

**Issue by harbiabe** [perlorg/perlweb#239]
Dear,
 
I have an issue with PSN. I have installed the updated version of Strawberry Perl 5.26.0.1 (32bit) and ActivePerl . However, I couldn't install PSN successfully.

Why? please help me as soon as possible (my computer system is windows 10 32 bit )

Thank you,

**Comment by rspier** [comment]
This is not the place to ask Perl questions.  It's for issues with the perl website.  You could try the Perl beginners list, the bioperl list, or contract with ActivePerl for support.
