### ISSUE TITLE
http://xrl.us/installperlosx is offline since around 2 weeks

### ISSUE THREAD

**Issue by Apollon77** [perlorg/perlweb#244]
Hi,

is this known? Is there an ETA to get it back online?

**Comment by abh** [comment]
Fixed, nobody pointed it out until today. Thanks!

**Comment by Apollon77** [comment]
verified :-) Next time I know that I open a issue here ... I use this in travis-ci to install perl on osx environment and my osx jobs failed since 2-3 weeks :-)
