### ISSUE TITLE
5.24 Upgrade

### ISSUE THREAD

**Issue by loglem** [perlorg/perlweb#247]
Security is suggesting that our organization upgrades to 5.24 from 5.8.8.  Has anyone run into any complications with an upgrade? What should we expect?

**Comment by abh** [comment]
You're upgrading 11 years of improvements and changes, so... it depends. Personally I've upgraded a bunch of things with big jumps in the version of Perl like this and haven't run into any trouble with Perl, but sometimes modules I use have changed.

This isn't the right place to ask about this though. A mailing list or forum about some of the specific modules you use might be more appropriate.

**Comment by karenetheridge** [comment]
@loglem this is a good article that will give you a starting point: https://www.activestate.com/blog/2017/05/upgrading-perl-modern-version-activestate-guide
