### ISSUE TITLE
Please set up resume.perl.org for hosting the perlresume app

### ISSUE THREAD

**Issue by shlomif** [perlorg/perlweb#248]
Hi!

See https://github.com/vti/perlresume.org/issues/15 - the very cool site perlresume by @vti went down after the perlresume-dot-org domain got lost and we would like to restore it under the perl.org domain. The source code for it is available at https://github.com/vti/perlresume.org and is written in Perl and is easy to deploy (not sure about its licence though).

Thanks!

**Comment by rspier** [comment]
For security and other reasons, we are extremely conservative about setting up new applications on the perl.org domain.

If you wish to resuscitate this site, we suggest you register a new domain for it.

**Comment by abh** [comment]
It's missing a license, indeed. Also "easy to run" doesn't mean "free to maintain"...
