### ISSUE TITLE
CSS lost cdn.perl.org/tucs/style.css?9 returns 404

### ISSUE THREAD

**Issue by LorenzoTa** [perlorg/perlweb#250]
hello, it appears, probalby since yesterday afternoon, that www.perl.org has lost it's css

both [cdn.perl.org/tucs/style.css?9](url) and [cdn.perl.org/tucs/style.css?10](url) return infact a 404

the same issue is affecring http://search.cpan.org/

**Comment by abh** [comment]
Thanks, I will have a look.

**Comment by abh** [comment]
Fixed, thank you. The CDN had cached a bunch of 404's from yesterday when we had an outage in the kubernetes cluster, doh.  https://github.com/jcmoraisjr/haproxy-ingress/issues/72
