### ISSUE TITLE
Book feature from Packt

### ISSUE THREAD

**Issue by packtpartner** [perlorg/perlweb#255]
Hi,   

We would request you to feature the following Book on http://learn.perl.org/books/ 

Perl 6 Deep Dive - https://www.amazon.com/dp/178728204X - This book is an end-to-end guide that will help non-Perl developers get to grips with the language and use it to solve real-world problems.

Thanks

**Comment by rspier** [comment]
That page only has Perl 5 books on it.  You probably want to find the perl6 website.

**Comment by packtpartner** [comment]
Thanks for your reply and noted.
