### ISSUE TITLE
events. TPC in SLC !

### ISSUE THREAD

**Issue by myrrhlin** [perlorg/perlweb#261]
click on events, from the home page:
https://www.perl.org/events.html

has no mention of TPC 2018, no link to https://perlconference.us/
and TPC is also not on the google calendar shown there.

also, referring to the oscon as "the perl conference" on the right side is going to confuse people, since TPF has had the rights to the name since 2016. 
The references to YAPC should at least include references to the new name, and update links.

**Comment by rspier** [comment]
@ranguard Do you know who maintains the "Worldwide Perl Conferences" calendar?  It's pretty sparse... maybe we should just remove it?  the TPR calendar seems better maintained.

**Comment by toddr** [comment]
I have opted to just manually list things for now. At least people know where to go to get them updated. 3dded49c7e6f7f88d3858dbe0b92af5ec3b75f6b

**Comment by toddr** [comment]
This ticket can be closed.
