### ISSUE TITLE
Content not rebuilding on merge?

### ISSUE THREAD

**Issue by ranguard** [perlorg/perlweb#267]
http://dev.perl.org/perl5/ - shows `Latest development release is Perl 5.27.5` - but..

https://github.com/perlorg/perlweb/commit/6530b6b69cda4a000692e44634b066ef32ead91c

I've noticed this on a few merges recently that don't seem to be updating?

Does something need kicking?

Thanks

**Comment by rspier** [comment]
A manual git step is still required right now.  I've done it. @abh Are we ready to eliminate it?

**Comment by rspier** [comment]
At Sat Sep 22 21:08:54 2018 -0700, we switched to pull directly from GitHub instead of our private git server.
