### ISSUE TITLE
cpanratings - unescaped distribution in title can lead to XSS attack

### ISSUE THREAD

**Issue by perlancar** [perlorg/perlweb#270]
For example:

    https://cpanratings.perl.org/rate/?distribution=Foo-<script>alert("whoa")</script>

will show a Javascript alert dialog box. 

UPDATE: fix the URL.

**Comment by MartinMcGrath** [comment]
I can't reproduce this by visiting this URL. Chromium v65

**Comment by perlancar** [comment]
The URL seems to have been escaped prior to copy-pasting. Try this:

    https://cpanratings.perl.org/rate/?distribution=Foo-<script>alert("whoa")</script>

**Comment by perlancar** [comment]
Firefox 59.0.2 and 60.0 on Linux. Both still display the alert dialog on my computer.

**Comment by rspier** [comment]
No longer an issue because we're no longer accepting edits to cpanratings.
