### ISSUE TITLE
Perl News is quite out of date

### ISSUE THREAD

**Issue by zakame** [perlorg/perlweb#278]
![image](https://user-images.githubusercontent.com/110625/42704677-5d3ff8a0-8703-11e8-83c7-ccda57e2a28f.png)

It seems to be pointing at https://feeds.feedburner.com/PerlNews; perhaps that needs reconfiguring the Feedburner to use https://www.perl.com/index.xml as well?

**Comment by rspier** [comment]
I just updated the cronjob.  I'll check in on it after it's had a chance to run.

**Comment by zakame** [comment]
Thanks @rspier @abh, seems to be updating now

![image](https://user-images.githubusercontent.com/110625/42858385-e367761c-8a80-11e8-9880-29c888e7da37.png)

**Comment by abh** [comment]
@zakame thanks for the reminder!
