### ISSUE TITLE
Restore par.perl.org

### ISSUE THREAD

**Issue by jwrightecs** [perlorg/perlweb#282]
par.perl.org no longer exists in DNS, but there are links in active modules on CPAN pointing to the domain.  The last version of the par site that doesn't redirect to either perl6.org or par.wikia.com (now defunct) is https://web.archive.org/web/20140217033420/http://par.perl.org:80/wiki/Main_Page

**Comment by rspier** [comment]
It would be better to update the modules pointing to the wrong place.

**Comment by tehmoth** [comment]
That seems to be the issue, par.perl.org seems like the correct place, as it was until it was removed without a replacement.

**Comment by rspier** [comment]
Since there isn't a replacement, and nobody is maintaining a par site, there's nowhere to point it.

**Comment by abh** [comment]
We didn’t remove the site. Someone else was running it and if I remember right let it either go away or fall into disrepair (spam, etc), so we removed the DNS entry that was either going nowhere or going to spam/viruses/etc.
