### ISSUE TITLE
http://strawberryperl.com/ is gone

### ISSUE THREAD

**Issue by IceflowRE** [perlorg/perlweb#283]
`http://strawberryperl.com/` is not a valid link anymore and should probably removed from the download links.

**Comment by smpeters** [comment]
Seems to work for me.

**Comment by IceflowRE** [comment]
![screenshot_2019-01-25 site not found dreamhost](https://user-images.githubusercontent.com/10883690/51773630-b952e180-20ef-11e9-97b8-d38f98b82240.png)

**Comment by smpeters** [comment]
Since images in emails don't show up...

<img width="1267" alt="screen shot 2019-01-25 at 3 28 35 pm" src="https://user-images.githubusercontent.com/38994/51773997-55f88d80-20b6-11e9-990b-22575396bff8.png"

**Comment by IceflowRE** [comment]
Interesting
