### ISSUE TITLE
Some list mail being rejected by Gmail with IPv6AuthError

### ISSUE THREAD

**Issue by treyharris** [perlorg/perlweb#286]
I just received a message from ezmlm with the warning that some of the messages to `perl6-users` bounced on my provider’s (Gmail’s) side. From the bounce message, Gmail is warning:

```
Our system has detected that this message does not meet IPv6 sending
guidelines regarding PTR records and authentication. Please review
https://support.google.com/mail/?p=IPv6AuthError for more information.
```

https://support.google.com/mail/?p=IPv6AuthError suggests this is not an issue I can fix on my end.

A possible reason this is happening to me and not others: I’m using a forwarder from my  email domain to my `@gmail.com` address. I have no idea why it’s happening for only a few of the messages sent to the list (I received someone’s reply to one of the bounced messages, for instance).

If you have a way for me to provide the entire original message in private form, so I don’t have to broadcast my forwarding details to the Internet, please let me know how.

Also, I have my CPAN and Gmail email addresses associated with my subscription so I can successfully send _outgoing_ mail to the lists from those addresses if my client doesn’t rewrite the `From:` header. I’d be happy to change my incoming address on the mailing list to one of those, if the issue is at my forwarder and switching to CPAN’s would fix this—but I can’t figure out how to do so in the interface.

**Comment by rspier** [comment]
This should have been fixed two weeks ago.  We neglected to properly configure IPv6 after a server move.   Bounces are delayed because they're processed in batches.

Please do *not* switch to the CPAN forwarder.  It will likely not result in improved performance.
