### ISSUE TITLE
PI declaration file.

### ISSUE THREAD

**Issue by shaneferk111** [perlorg/perlweb#304]
Hello, i was just wondering what file PI was declared in in Perl 5.28.2, if anyone could help me with this i would really appreciate it thank you.

**Comment by rspier** [comment]
This is the wrong place to ask this question.  This is for issues with the perl.org websites, not about perl itself.  

Try https://lists.perl.org/list/beginners.html

**Comment by MartinMcGrath** [comment]
Also [Seekers of Perl Wisdom](https://perlmonks.org/?node=Seekers%20of%20Perl%20Wisdom), [Perl on reddit](https://old.reddit.com/r/perl/new/).
