### ISSUE TITLE
Issues with ActiveState Perl download links

### ISSUE THREAD

**Issue by KenCotterill** [perlorg/perlweb#315]
I encountered some issues with ActiveState Perl links on the "Perl Download" page.

As part of a response on PerlMonks, these are documented in:
https://www.perlmonks.org/?node_id=11115065

**Comment by karenetheridge** [comment]
I'm not sure I understand what the issue is? If a specific link has an error in it, you can submit a pull request to fix it.

**Comment by KenCotterill** [comment]
G'day Karen,
      
      I thought the description was clear and detailed; however, as
      you're having difficulties, perhaps that's not the case.
      
      If you can be more specific regarding what information is missing,
      ambiguous, or otherwise lacking clarity, I'll aim to rectify that.
      
      Cheers,
      
      Ken.
      
    
    On 05-Apr.-20 12:03 pm, Karen Etheridge
      wrote:
    
    
      
      I'm not sure I understand what the issue is? If a specific link
        has an error in it, you can submit a pull request to fix it.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perlorg/perlweb/issues/315#issuecomment-609117006",
"url": "https://github.com/perlorg/perlweb/issues/315#issuecomment-609117006",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rspier** [comment]
The links to Activestate are fine and correct.  I can't replicate this in Firefox or Chrome.  The error messages you pasted to PerlMonks look like something configured on your local system or network.  Actually, a little research shows that it's probably something OpenDNS is doing.  I suggest you talk to them or Activestate.

Either way, there's nothing to be done on the perl.org side.
