### ISSUE TITLE
perlfaq is out of date

### ISSUE THREAD

**Issue by karenetheridge** [perlorg/perlweb#317]
I see perlfaq html files in docs/learn/faq/ -- they haven't been updated since 2018.

I'd be happy to send pull requests to update these whenever I do a new perlfaq release, but I don't see a readme on how the html files are generated. please add one :)

**Comment by abh** [comment]
@karenetheridge I think it's from `bin/update_faq.pl` if you want to give it a try.

**Comment by rspier** [comment]
This was fixed in 835a03c58aef0c40f40cc66c4a96597a897ae5b5 by @Grinnz
