### ISSUE TITLE
outdated news page at dev.perl.org

### ISSUE THREAD

**Issue by rwp0** [perlorg/perlweb#325]
hello,

url: https://dev.perl.org/perl5/news/

the last entry being `perl 5.24.1`, released on _january 14, 2017_

also, having rss on this page could be useful, having a shorter content than the metacpan [perl](https://metacpan.org/release/perl) distribution page (which has [feeds](https://metacpan.org/feed/distribution/perl) available), but that being just a suggestion, not the main concern

and, thanks for upgrading the core documentation on perldoc.perl.org to 5.32!

---

(cross-)posting from [Perl/perl5 #18045](https://github.com/Perl/perl5/issues/18045) (at correct repository)

**Comment by rspier** [comment]
I've replaced it with a RSS feed of releases.  It's differently bad, but at least it's not years out of date.  The old list was previously manually updated by whoever was doing the release, but that clearly fell off the checklist.

If all goes well, it should go live in a few hours.

**Comment by rwp0** [comment]
awesome, thanks

**Comment by rspier** [comment]
Confirmed that it's live and working as intended.
