### ISSUE TITLE
Randal Schwartz' Articles is down

### ISSUE THREAD

**Issue by LadyAleena** [perlorg/perlweb#333]
[Randal Schwartz' Articles](http://www.stonehenge.com/merlyn/columns.html) is [down](https://downforeveryoneorjustme.com/stonehenge.com?proto=http&www=1) on [Books and More](https://www.perl.org/media.html).

File: https://github.com/perlorg/perlweb/blob/master/docs/www/media.html#L64

**Comment by MartinMcGrath** [comment]
I see the articles and the page you link to says Stonehenge is up.

**Comment by LadyAleena** [comment]
Weird, it still says that it is not just me that it is down for.
