### ISSUE TITLE
A few broken links in the list of of mailing lists

### ISSUE THREAD

**Issue by gugod** [perlorg/perlweb#340]
A few mailing lists listed here seems to be hosted on Yahoo Groups, a service that is recently shutdown:

https://lists.perl.org/all.html

For example, perl-beginner:

https://lists.perl.org/list/perl-beginner.html

Those informations are still referring to Yahoo Groups.

If there are no alternatives, perhaps these mailing lists should be removed from lists.perl.org

**Comment by rspier** [comment]
Thanks!  Should be fixed in a few minutes after it deploys.
