### ISSUE TITLE
datetime.perl.org is down

### ISSUE THREAD

**Issue by simbabque** [perlorg/perlweb#344]
It looks like datetime.perl.org doesn't have a DNS entry.

I get `DNS_PROBE_FINISHED_NXDOMAIN` in Chrome and 

```
$ ping datetime.perl.org
ping: datetime.perl.org: Name or service not known
```

**Comment by rspier** [comment]
@autarch : If the site is dead, i'll drop the DNS and remove the references.

**Comment by autarch** [comment]
> @autarch : If the site is dead, i'll drop the DNS and remove the references.

Yes, please do so. Sorry for not following up earlier.

**Comment by rspier** [comment]
Thanks!
