### ISSUE TITLE
Links to yapc.tv may have linkrot

### ISSUE THREAD

**Issue by zmughal** [perlorg/perlweb#366]
I noticed that <http://yapc.tv/> is linked from <https://www.perl.org/learn.html> and no longer points to the described videos.

I believe that @ash was running yapc.tv.

**Comment by zmughal** [comment]
At least for the Moose video listed there, this might make for a replacement <https://www.youtube.com/watch?v=LKXvG6VKew4>.

**Comment by rspier** [comment]
Thank you.  For now I've removed the Videos section until another curated source is found.

**Comment by zmughal** [comment]
Thanks. I remember at one point @szabgab had <https://github.com/szabgab/perltv.org>. Not sure if there a plans to bring that back, but there are curated data in that repository.

**Comment by szabgab** [comment]
I don't have any plans with my repo. Feel free to take it, set it up on some domain or even inside perl.org
