### ISSUE TITLE
Update whitepapers examples

### ISSUE THREAD

**Issue by renderorange** [perlorg/perlweb#375]
If the whitepaper examples are to `help you in understanding why modern Perl is a good tool for many different types of project and also to provide pointers for those starting out in Perl`, we should be cautious to steer people to examples that demonstrate when projects become abandoned.

**Comment by renderorange** [comment]
For example, https://www.perl.org/about/whitepapers/perl-loadbalancer.html lists Perlbal, a 10 year stale project with several open issues and several broken testing builds.  It could be easy to associate stale project with stale language.

**Comment by abh** [comment]
LGTM. @rspier?
