### ISSUE TITLE
pdl.perl.org CNAME update (and email to webmaster@ bouncing)

### ISSUE THREAD

**Issue by mohawk2** [perlorg/perlweb#378]
This may be the wrong forum, but I did this from https://noc.perl.org/:
> For all other issues with perl.org services, please send an email to webmaster at perl.org.

and it bounced:
```
The mail system
<rt-web@rtperl.dev>: Command died with status 29:
    "/home/rt/rt/bin/rtperl-mailgate". Command output: couldn't write to log
    file: Illegal seek at
    /home/rt/perlbrew/perls/rt/lib/site_perl/5.18.1/Mail/Audit.pm line 752
```

...and opening an issue here seemed equivalent according to https://www.perl.org/siteinfo.html:
> You can email us at webmaster at perl.org. Please open an [issue](https://github.com/perlorg/perlweb/issues) or better yet a pull request on our [github](https://github.com/perlorg/perlweb/) account

The substantive request was that the Perl NOC update the pdl.perl.org CNAME to point at pdlporters.github.io - I believe I’ve configured GitHub correctly. Please let me know if this poses a problem or if there’s anything you need from me! (I'm current PDL maintainer)

**Comment by rspier** [comment]
The ticket was actually created successfully, but it couldn't write to the log.  Sorry about that, weird arbitrary limit.  Will deal with your DNS request in the RT ticket.

**Comment by mohawk2** [comment]
Amazing, thanks!
