### ISSUE TITLE
Subscription to moose@perl.org does not work

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [perlorg/perlweb#389]
moose mail list is listed at https://lists.perl.org/all.html

I am trying to send e-mail to  moose-subscribe@perl.org (as advised at https://lists.perl.org/list/moose.html)  , and get following error
```
<moose-subscribe@perl.org>: host perl.mx.develooper.com[147.75.38.233] said:
    554 5.7.1 <moose-subscribe@perl.org>: Recipient address rejected: Access
    denied (in reply to RCPT TO command)
```

If I try some other list (I tried sending mail to beginners-subscribe@perl.org) it works well and I am getting subscription confirmation mail back.

I guess something should be fixed, or if list does not work intentionally, there should be some notice abut it in the web.

**Comment by rspier** [comment]
lists.perl.org was out of date.  The moose list hadn't had posts for years and was shut down.
