### ISSUE TITLE
Delete review

### ISSUE THREAD

**Issue by abh** [perlorg/perlweb#4]
Add feature to let a user delete a review.  The review should still be stored in the database, but not be shown on the home page and just be shown as "this review has been deleted" at the bottom of the distribution and user page.

**Comment by mrdvt92** [comment]
+1 - I have a few reviews that I've changed to " " after they are irrelevant.

**Comment by capripot** [comment]
Yeh please, where is the delete button?

**Comment by Cjdcoy** [comment]
up

**Comment by rspier** [comment]
Bulk closing all cpanratings issues, as the site has been in read-only mode for over a year.  https://log.perl.org/2018/06/cpan-ratings-read-only.html
