### ISSUE TITLE
https://www.cpan.org/modules/02packages.details.txt not updating

### ISSUE THREAD

**Issue by karenetheridge** [perlorg/perlweb#415]
The timestamp at the top of https://www.cpan.org/modules/02packages.details.txt shows that it hasn't been pulling from PAUSE for a few days now. This means that any cpan client using this site as the source won't be getting updates to any modules.

**Comment by andk** [comment]
Thanks, Karen! For a reference, pause currently has a 02packages.details.txt with this line:

``` text
# grep Last-Updated /home/ftp/pub/PAUSE/modules/02packages.details.txt  
Last-Updated: Wed, 13 Dec 2023 19:17:02 GMT
```

**Comment by DrHyde** [comment]
http://www.cpan.org/authors/RECENT-1M.yaml also appears to not be updated

**Comment by rspier** [comment]
One of the steps in the pipeline had gotten stuck a few times.  It seems happy now.
